config/routes.rb
MyToons::Application.routes.draw do
  
root :to => 'toons#index'
  devise_for :users 

  resources :products
  resources :toons do
    resources :comments, :only => [:create, :destroy]
  end
  match 'dashboard_systemadmin' => "users#systemadmin_dashboard", :as => "dashboard_systemadmin" ,:via => [:delete,:get,:post]
  match 'dashboard_moderator' => "toons#dashboard_moderator", :as => "dashboard_moderator" ,:via => :get
  match 'dashboard_publisher' => "toons#dashboard_publisher", :as => "dashboard_publisher" ,:via => :get
  match 'toons/:id/publish'=>"toons#publish",:as=>:publish
  match 'toons/:id/approve'=>"toons#approve",:as=>:approve
  match 'toons/:id/disapprove'=>"toons#disapprove",:as=>:disapprove
  match 'users/:id/delete'=>"users#delete",:as=>:delete
  match 'myshow' => "toons#myshow", :as => "myshow" ,:via => :get
  resources :users do
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :SystemAdmin
      can :manage, :all
    elsif  user.has_role? :user
      can [:index,:show, :new, :create,:myshow], Toon
    #      cannot [:new,:create], Toon
    elsif user.has_role? :Moderator
      can [:index,:show ,:dashboard_moderator, :approve,:new,:create ,:disapprove,:myshow] , Toon
    elsif user.has_role? :Publisher
      can [:index,:show ,:dashboard_publisher, :publish,:new,:create ,:myshow] , Toon

    else
      can [:index,:show , :new , :create,:myshow], Toon
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :user
   belongs_to :toon

   attr_accessible :body

   validates :user_id, :presence => true
   validates :toon_id, :presence => true
   validates :body, :presence => true, :length => { :maximum => 5000 }     # spam protection

   default_scope :order => 'comments.created_at asc'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/toon.rb
class Toon < ActiveRecord::Base
  belongs_to :user
  attr_accessor :image
  mount_uploader :image, ImageUploader
  validates :name,:why_fav ,:description,:image,:presence => true
  validates :name,:length => { :minimum => 6, :maximum => 20 },:on=>:create
  has_many :comments, :dependent => :destroy 
    def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
    end
    def self.unapproved(user)
        self.where('state = ? AND created_by != ?', "inactive" , user.id)
      end
      def self.approved(user)
        self.where('state = ? AND created_by != ? ', "approved" , user.id)
      end
       def self.published()
        self.where('state = ?', "published")
      end
      def self.myshow(user)
         self.where('created_by = ? ',  user.id)
      end
   end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates :first_name,:last_name,:phone_number, :presence => true
  validates :phone_number, :numericality => { :only_integer => true }
  validates :phone_number, :length => {:is => 10}
  validates :phone_number, :numericality => { :only_integer => true }
  validates :password, :presence =>true, :length => { :minimum => 6, :maximum => 16 },:on=>:create
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, :dependent => :destroy
  has_many :toons, :dependent => :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,:first_name,:last_name,:phone_number, :remember_me,:role_ids

  after_create :creating_role_for_external_users
  def creating_role_for_external_users
    self.add_role :User
  end

  def fullname
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 helper_method :redirect_to
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  # create a comment and bind it to an toon and a user
  def create
    @toon = Toon.find(params[:toon_id])
    @comment = @toon.comments.build(params[:comment])
    @comment.user = current_user
      if @comment.save
        redirect_to(@toon, :notice => 'Comment was successfully created.') 
      else
        redirect_to(@toon) 
      end
  end

  # remove a comment
  def destroy
    @comment = current_user.comments.find(params[:id])
    @toon = Toon.find(params[:toon_id])
    @comment.destroy
    redirect_to @toon
  end
end

app/controllers/toons_controller.rb
class ToonsController < ApplicationController
  # before_filter :authenticate_user! , :except => [:index , :show]
  #  before_filter :only_allow_admin, :only => [ :index ]
  load_and_authorize_resource

  def new
    @toon = Toon.new
  end

  def create
    @toon = Toon.new(params[:toon])
    @toon.created_by = current_user.id
    if @toon.save
      redirect_to toons_path
      flash[:notice]= "Your Toon has been sent for approval..It will be published shortly"
    else
      render "new"
    end
  end

  def index
    #    raise current_user.inspect
    @search1 = Toon.search(params[:search]).published().where("name like ?", "%#{params[:q]}%")
     @search = Toon.search(params[:search])
    @toons=@search.published().order('created_at DESC').page(params[:page]).per(4)
    @toons_corousel=Toon.published()
    respond_to do |format|
      format.html
      format.json { render :json => @search1.map(&:attributes)}
    end
  end
  
  def show
    @toon=Toon.find(params[:id])
    @comments = @toon.comments.all
  end

  def myshow
    @search = Toon.search(params[:search])
    @toons=@search.myshow(current_user).order('created_at DESC' ).page(params[:page]).per(4)
    # @toonss=Toon.myshow(current_user)

  end

  def dashboard_moderator
    @unapproved = Toon.unapproved(current_user).order('created_at DESC' )
  end

  def dashboard_publisher
    @approved = Toon.approved(current_user).order('created_at DESC' )
    @toons=@unapproved
  end

  def approve
    @toon = Toon.find(params[:id])
    @toon.state = "approved"
    @toon.save
    flash[:notice]= "Approved Succesfully"
    redirect_to dashboard_moderator_url
    flash[:notice]= "Approved Succesfully"
  end

  def disapprove
    @toon = Toon.find(params[:id])
    @toon.state = "disapproved"
    @toon.save
    redirect_to dashboard_moderator_url
    flash[:notice]= "Disapproved Succesfully"
  end

  def publish
    @toon = Toon.find(params[:id])
    @toon.state = "published"
    @toon.save
    redirect_to dashboard_publisher_url
    flash[:notice]= "Published Succesfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    respond_to do |format|
      format.html
      format.json { render :json=> UsersDatatable.new(view_context) }
    end
  end

  def systemadmin_dashboard
    @users=User.page(params[:page]).per(25)
    # @userdashboard=User.current_user
    @roles = Role.all

  end

  def update
    @roles = Role.all
    @user = User.find(params[:id])
    @user.role_ids = params[:user_role]
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to dashboard_systemadmin_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def after_sign_in_path_for(resource)
    #    raise current_user.inspect
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    sign_up_url = url_for(:action => 'new', :controller => 'registrations', :only_path => false, :protocol => 'http')
    if (request.referer == sign_in_url)
    super
    elsif (request.referer == sign_up_url)
      root_path
    else
      if  current_user.has_role? :Moderator
        dashboard_moderator_url
      elsif current_user.has_role? :Publisher
        dashboard_publisher_url
      elsif current_user.has_role? :SystemAdmin
        #        raise current_user.inspect
        dashboard_systemadmin_url

      elsif current_user.has_role? :User
        request.referer || stored_location_for(resource) || root_path
      else
        request.referer || stored_location_for(resource) || root_path
      end
    end
  end

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/toons_helper.rb
module ToonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyToons" %></title>
    <%= csrf_meta_tags %> <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
		<![endif]-->
    <%= stylesheet_link_tag "application", "token-input",:media => "all" %>
<%#= javascript_include_tag 'jquery', 'rails.validations'-%>
    <%= javascript_include_tag  'jquery'%>
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <div class="wrapper">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
            <!--           <img src="images/cartoon.jpg"  alt="Cartoon"/> -->
            <%= link_to "MyToons", root_url,:class=>"brand"  %>  
            <div class="container-fluid nav-collapse">              
              <% if current_user%>
                <div class="btn-group pull-right">
                  <div class="btn-group">
                    <button class="btn">
                      <i class="icon-user"></i> <%= current_user.fullname %>
                    </button>
                    <button class="btn dropdown-toggle" data-toggle="dropdown" >
                      <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to 'Edit Profile',edit_user_registration_path %>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to 'Logout' , destroy_user_session_path, :method=>'delete', :class=>"logout" %>
                      </li>
                    </ul>
                  </div>
                </div>
              <% else%>
                <div class="pull-right">

                  <%= link_to  content_tag(:span, " Login" ,:class=>"icon-user") ,  new_user_session_path,  :class=>"btn login",:remote => true %>
                </div>
              <% end %>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list nav_links" style="display: block">
               
                <% if user_signed_in?%>                  
                  
                    <%  if current_user.has_role? :Moderator   %>
                     <%= nav_link "Dashboard", dashboard_moderator_url %>
                     
                     
                   <%= nav_link "Home", root_url %> 
                 
                    <% elsif current_user.has_role? :Publisher %>
                    <%= nav_link "Dashboard", dashboard_publisher_url %></li>   
                                    
                     
                    <%= nav_link "Home", root_url %> 
                                  
                   
                    <% elsif current_user.has_role? :SystemAdmin %>
                      <%= nav_link  "Dashboard", dashboard_systemadmin_url  %>                   	
                      <%= nav_link "Home", root_url %>  
                      <% elsif current_user.has_role? :User %>
                    	<%= nav_link "Home", root_url %>                     
                    <% end %>        
                  
                    <%= nav_link  "My Toons", myshow_path %>
                

                <% else %>
                	 <%= nav_link "Home", root_url %>                 
                   	 <%= nav_link 'Sign up', new_user_registration_path  %>                 
                <%end%>
              </ul>

            </div><!--/.well -->
          </div><!--/span-->         
          <div class="span9" >
            <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <% end %>
          </div>          
          <div id="main" class="span9" style="margin-bottom: 25px">
            <%= yield %>
          
             <div style="clear: both;">
          	
          </div></div>
        </div><!--/row-->


        <!-- /container -->
        <div>
          <div class="overlay" ></div>
          <div class="login-div" >

          </div></div></div></div>	
       
          
   <footer>
    <p>

					Company 2012 &copy; MyToons
    </p>
  </footer>
  <!-- Javascripts
		================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application","jquery.tokeninput" %> 
</body>
</html>

app/views/toons/_form.html.erb
<table class="table_newtoon">
	<tr>
		<td><%= form.label :Name %></td>
		<td><%= form.text_field :name ,:placeholder=>"Toon Name" %></td>
	</tr>
	<tr>
		<td><%= form.label :Description %></td>
		<td><%= form.text_area :description ,:placeholder=>"Describe your Fav Cartoon", :cols=>20,:rows=>3,:style=>"resize: none;"  %></td>
	</tr>
	<tr>
<!-- 		<td> <%= form.label :Upload_Toon %></td>
		<td>
		<div class="upload">
			<input type="text" value=""  placeholder="Upload Your favourite cartoon" />
			<input type="button" value="Upload " class="btn btn-info" /><%= form.file_field :image %>
		</div></td> -->
		
			<td> <%= form.label :Upload_Toon %> </td>
		<td> <%= form.file_field :image, :class=>"upload" %>
		 </td>
		
	</tr>
	<tr>
		<td><%= form.label :Why_favourite %></td>
		<td><%= form.text_area :why_fav ,:placeholder=>"Why is it Your fav Toon" , :cols=>20,:rows=>3,:style=>"resize: none;" %></td>
	</tr>
</table>

app/views/toons/_toons.html.erb
<table class="table-striped table-condensed table_css"><% @toons.each do |toon| %>

<tr><td><div class="span11" style="float: left; clear: both; margin-left: 30px !important; padding: 30px 0;">
	<div class="span2" style="float:left;">
		<%= image_tag(toon.image_url, :alt => "test image", :style => "width:150px ;height:100px") %>
	</div>
	<div class="span9 toon_index" style="float: left;">		
			<h5>Name : <a><%= link_to toon.name , toon_path(toon)%></a></h5>
			<h5> Description : </h5><span><%= toon.description[0,150] %> ...</span>
			<h5> Why Favourite : </h5><span><%= toon.why_fav[0,150] %> ...</span>
	</div>
</div></td></tr>
<% end %>
</table>

app/views/toons/dashboard_moderator.html.erb
<h4>Listing Toons</h4>
<br />

<div class="toon_index">
<table class="table .table-striped">
  <tr>
    <th>Toon Name</th>
    <th>Toon Description</th>
    <th>Why Fav</th>
  </tr>

<% @unapproved.each do |toon| %>
  <tr >
    <td><%=h toon.name %></td>
    <td style=" width: 227px;"><span><%=h toon.description[0,100] %> ...</span></td>
    <td style=" width: 227px;"><span><%=h toon.why_fav[0,100] %> ...</span></td>
    <td><%= link_to 'Show', toon %></td>
    
    <td><%= link_to 'Approve',approve_path(toon), :confirm => 'Are you sure?' %></td>
    <td><%= link_to 'Disapprove',disapprove_path(toon), :confirm => 'Are you sure?' %></td>

  </tr>
<% end %>
</table>
</div>

<br />

app/views/toons/dashboard_publisher.html.erb
<h4>Unpublished Toons </h4>
<br />
<div class="toon_index">
<table class="table .table-striped">
  <tr>
    <th>Toon Name</th>
    <th>Toon Description</th>
    <th>Why Fav</th>
  </tr>

<% @approved.each do |toon| %>
  <tr >
    <td ><%=h toon.name %></td>
    <td style=" width: 227px;"><span><%=h toon.description[0,100] %> ...</span></td>
    <td style=" width: 227px;"><span><%=h toon.why_fav[0,100] %> ...</span></td>
    <td><%= link_to 'Show', toon %></td>
    <td><%= link_to 'Publish',publish_path(toon), :confirm => 'Are you sure?' %></td>

  </tr>
<% end %>
</table>
</div>

app/views/toons/index.html.erb
<h4>Listing Toons</h4>
<br />
<%= form_tag toons_path, :method => :get, :id=> "toons_search"  do %>
  <%= text_field_tag :search, params[:search] ,:style=>"border:0"%>
  <%= submit_tag "Search", :name => nil ,:class=>"btn toon_sub" %>
<% end %>
<div style=" clear: both; padding-right: 30px;">
<p>
  <% if user_signed_in? %>
      <%= link_to " New Toon", new_toon_path , :class=>"btn icon-plus btn-primary"%><br />
    <% else %>
    <%= link_to " New Toon", new_user_session_path, :class=>"btn icon-plus login btn-primary" , :remote => true %><br />
  <% end %>
</p>
</div>
<div style="float:left; clear: both;">
<div id="toons" >
  <%= render 'toons' %>
  </div>	
		<%= paginate @toons%>	
</div>
<%if @toons_corousel.count > 5 %>
<div style="float: left; clear: both;height: 200px;">
  <div class="slideShowContainer">
    <div class="imagesContainer">
      <ul class="carousel11">
        <% @toons_corousel.each do |t| %>
          <li>
            <%=link_to image_tag(t.image.url), toon_path(t) %>           
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <p class="slideShowControls">
    <span class="slideShowControls prev">&lsaquo;</span>
    <span class="slideShowControls next">&rsaquo;</span>
  </p>
</div><%end%>

app/views/toons/index.js.erb
$('#toons').html('<%= escape_javascript(render("toons")) %>');

app/views/toons/myshow.html.erb
<h4>Listing Toons</h4>
<br/><br/><br/>
<div id="toons" style="float:left; clear: both;">
	
<%if @toons.blank?%>
<h3>No toons to Display...</h3>
<% else %>
 <table class="table-striped table-condensed table_css"><% @toons.each do |toon| %>
      <tr><td><div class="span11" style="float: left; clear: both; margin-left: 30px !important; padding: 30px 0;">
            <div class="span2" style="float:left;">
              <%= image_tag(toon.image_url, :alt => "test image", :style => "width:150px ;height:100px") %>
            </div>
            <div class="span9 toon_index" style="float: left;">
              <h5>Name: <%= link_to toon.name , toon_path(toon)%></a> <span style="float:right">Toon Status:<sapn class="toon_status"><%= toon.state %></sapn> </span> </h5>
              <h5> Description : </h5><span><%= toon.description[0,150] %> ...</span>
              <h5> Why Favourite : </h5><span><%= toon.why_fav[0,150] %> ...</span>
            </div>
          </div></td></tr>
    	<% end %>
   
  </table> 	
		<%= paginate @toons%>
	<% end %>	
</div>

app/views/toons/new.html.erb
  <h3>Create Your Toon</h3>

            <%= form_for @toon  ,:validate => true   do |f| %>
            
            <%= render :partial => "form", :object => f %>
            <%= f.submit "Create Toon", :class=>"btn btn-inverse",:style=>"margin:10px 0 0 212px;"  %>
            <% end %>

app/views/toons/show.html.erb
<div class="span12 toons_show" >
	<%= hidden_field_tag 'show_login',@selected_login%>
	<div class="span2" style="float: left; margin-top: 15px; width: 275px; margin-left: 0px;	">
		<%= image_tag(@toon.image_url, :alt => "test image", :style =>
		"width:175px;border:1px solid #DFE3E6; height:160px; padding-bottom:
		5px;margin-left: 50px;") %>
		<div class="toon_name" >
			<a href="#" style="text-decoration:none; text-shadow: 2px 2px 2px #36a6c2;filter: dropshadow(color=white, offx=2, offy=2);"> <%= @toon.name %> </a></h5>
		</div>
	</div>
	<div class="span11" style="float: left; margin-top: 40px; margin-left:
	0px;  width: 690px;">
		<div>
			<% if current_user%>
			<span style="margin-left: 500px;">
			<%  if  ((current_user.has_role?  :Moderator) && (@toon.state == "inactive")) %>
			<%= link_to 'Approve',approve_path(@toon), :confirm => 'Are you sure?' ,:style=> "margin-right:15px;" , :class=>"btn btn-success"%>
			<%= link_to 'Reject',disapprove_path(@toon), :confirm => 'Are you sure?', :class=>"btn btn-danger" %>
			<% end%>
			<%  if  ((current_user.has_role? :Publisher) && (@toon.state == "approved")) %>
			<%= link_to 'Publish',publish_path(@toon), :confirm => 'Are you sure?' , :class=>"btn btn-success" %>
			<% end%>
			</span>
			<% end%>
			<h3 style="color: #4D5ECD;"> Description : </h3><%= @toon.description %>
		</div>
		<div style="padding-top: 20px;">
			<h3 style="color:#4D5ECD;"> Why
			Favourite : </h3><%= @toon.why_fav %>
		</div>
		<% if @toon.state=="published"%>
		<h3>Comments:</h3>
		 <% @comments.each do |comment| %>
                
                <div class="commentbody">
                    <div class="commenthead">               
                      <%=link_to comment.user.fullname %> :<span style="color:#777;"> <%= comment.body %><br /></span>
                      <span style="color:#474747"><%=time_ago_in_words(comment.created_at)%> ago</span> 
                      <% # display delete link only for comments written by this particular user %>
                      <% if user_signed_in? and comment.user_id == current_user.id %>
                          <span><%= link_to 'delete', toon_comment_path(@toon, comment), :confirm => 'Are you sure?', :method => :delete, :class => "" %></span>
                      <% end %> 
                    </div>
                    
                </div>  
            
        <% end %>
        
        <% # add a new comment %>   
            
                <% if user_signed_in? %>                   
                    <div class="commentbody">
                        <% if current_user.fullname == nil or current_user.fullname == '' %>
                            <div class="commenthead">
                                Please complete your <%= link_to "profile", edit_user_registration_path %> before posting comments.
                            </div>
                        <% else %>              
                            <div class="commenthead">
                                <%= current_user.fullname %> :
                            </div>
                            <div>
                                <%= form_for [@toon, current_user.comments.new ] ,:validate => true  do |f| %>
                                    <%= f.text_area :body,  :cols=>20,:rows=>2,:style=>"resize: none;" %><br />
                                    <%= f.submit "Add Comment",:class=>"btn" %>
                                <% end %>               
                            </div>          
                        <% end %>
                    </div>  
                <% else %>
                    <div class="signin">
                        Please <%= link_to "sign in", new_user_session_path,:class=>"login",:remote=>:true %> before posting a comment.
                    </div>
                <% end %>
     
		<%end%>
	</div>
</div>

app/views/users/_roles.html.erb
<%= form_for(user,:remote=>true, :html => { :style => 'height:85px;' }) do |f|  %> <div>
				 		Current Role : <%= @user.roles.first.try(:name) %><br />
 						Change Role : <%= select_tag "user_role", options_from_collection_for_select(@roles, "id","name") %>
  						<div><%=f.submit "Update" ,:class=>"btn btn-info" %></div>
<% end %>

app/views/users/_userslist.html.erb
<table id="users_list" class="table table-striped table-bordered table-condensed pretty" title="Users list" >
	<thead>
		<tr>
			<th> Full Name </th>
			<th> Phone Number </th>
			<th> Email </th>
			<th>Last Signed In</th>
			<th>IP Address </th>
			<th>Role </th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
			
			<% @users.each do |user| %>
			<tr>
				<td> <%= user.fullname %> </td>
				<td> <%= user.phone_number %> </td>
				<td> <%= user.email %> </td>		
				<td><%= user.last_sign_in_at %></td>		
				<td><%= user.last_sign_in_ip %></td>	
				 <td id="user<%=user.id%>_role" ><%= form_for(user,:remote=>true, :html => { :style => 'height:85px;' }) do |f|  %> <div>
				 		Current Role : <%= user.roles.first.try(:name) %><br />				 		
 						Change Role : <%= select_tag "user_role", options_from_collection_for_select(@roles, "id","name") %>
  						<div><%=f.submit "Update" ,:class=>"btn btn-info" %></div>
					<% end %>
				 </td>		
				<td><span class="delete"><%= link_to 'Destroy', user , :confirm=> 'Are you sure?', :method=> :delete%></span></td>
				
			</tr>			
			</tr>			
			<% end %>			
	</tbody>
</table>

app/views/users/index.html.erb
<table id="users_list1" class="table table-striped table-bordered table-condensed" title="Users list" data-source="<%= users_url(format: "json") %>" >
	<thead>
		<tr>			
			<th> Full Name </th>
			<th> Phone Number </th>
			<th> Email </th>
			<th> Last Signed In</th>			
		</tr>
	</thead>
	
	<!-- <tfoot>
		<tr>
			<td colspan="8" class="pagination"><%#= paginate @users%></td>
		</tr>
	</tfoot> -->
</table>

app/views/users/systemadmin_dashboard.html.erb
<!-- <div class="box">
	<p>
		<strong>Last Signed In : </strong> <%#= @userdashboard.last_sign_in_at if current_user %>
		<br />
		<strong>IP Address : </strong> <%#= @userdashboard.last_sign_in_ip if current_user %>
	</p>
</div> -->

<div>
	<%= render 'userslist'%>
</div>

app/views/users/update.js.erb
$("#user<%=@user.id%>_role").html('<%= escape_javascript(render :partial => "roles", :locals => {:user => @user })%>')